name: Check Pull Request
on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Unit Test
        id: unit-test
        run: |
          yarn install
          yarn run test:ci
